apiVersion: ko-pour.demo/v1alpha1
kind: Deployment
metadata:
  name: hello-world-node
  labels:
    application: hello-world-node
    owner: scottaculous
    cost-center: demo
    environment: demo
spec:
  architecture:
    reference: gcp-cloud-run-stateless-web-v1
  application:
    state: stateless
  data:
    database: none
  runtime:
    portEnvironmentVariable: PORT
  health:
    path: /healthz
    expectedStatus: 200
  security:
    access: public
    dataClassification: public
    processesSensitiveData: false
    requiresSecrets: false
  resources:
    cpu: 1
    memory: 512Mi
    gpu: 0
    minInstances: 0
    maxInstances: 3
